{% set version = "2.4.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-devtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/devtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/devtools/devtools_{{ version }}.tar.gz
  sha256: 38160ebd839acdec7ebf0699a085b4ab1ebd5500d3c57a9fa7ae484f1909904b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.3.0
    - r-desc >=1.4.1
    - r-ellipsis >=0.3.2
    - r-fs >=1.5.2
    - r-lifecycle >=1.0.1
    - r-memoise >=2.0.1
    - r-miniui >=0.1.1.1
    - r-pkgbuild >=1.3.1
    - r-pkgdown >=2.0.6
    - r-pkgload >=1.3.0
    - r-profvis >=0.3.7
    - r-rcmdcheck >=1.4.0
    - r-remotes >=2.4.2
    - r-rlang >=1.0.4
    - r-roxygen2 >=7.2.1
    - r-rversions >=2.1.1
    - r-sessioninfo >=1.2.2
    - r-testthat >=3.1.4
    - r-urlchecker >=1.0.1
    - r-usethis >=2.1.6
    - r-withr >=2.5.0
  run:
    - r-base
    - r-cli >=3.3.0
    - r-desc >=1.4.1
    - r-ellipsis >=0.3.2
    - r-fs >=1.5.2
    - r-lifecycle >=1.0.1
    - r-memoise >=2.0.1
    - r-miniui >=0.1.1.1
    - r-pkgbuild >=1.3.1
    - r-pkgdown >=2.0.6
    - r-pkgload >=1.3.0
    - r-profvis >=0.3.7
    - r-rcmdcheck >=1.4.0
    - r-remotes >=2.4.2
    - r-rlang >=1.0.4
    - r-roxygen2 >=7.2.1
    - r-rversions >=2.1.1
    - r-sessioninfo >=1.2.2
    - r-testthat >=3.1.4
    - r-urlchecker >=1.0.1
    - r-usethis >=2.1.6
    - r-withr >=2.5.0

test:
  commands:
    - $R -e "library('devtools')"           # [not win]
    - "\"%R%\" -e \"library('devtools')\""  # [win]

about:
  home: https://devtools.r-lib.org/, https://github.com/r-lib/devtools
  license: MIT
  summary: Collection of package development tools.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
