{% set version = "1.13.6" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-devtools
  version: {{ version|replace("-", "_") }}

source:
  fn: devtools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/devtools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/devtools/devtools_{{ version }}.tar.gz
  sha256: b9749de8b095bd4983ef95a7700e53e4295a747fd20e9eae77dc372f5b2236b5

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-digest
    - r-git2r >=0.11.0
    - r-httr >=0.4
    - r-jsonlite
    - r-memoise >=1.0.0
    - r-rstudioapi >=0.2.0
    - r-whisker
    - r-withr

  run:
    - r-base
    - r-digest
    - r-git2r >=0.11.0
    - r-httr >=0.4
    - r-jsonlite
    - r-memoise >=1.0.0
    - r-rstudioapi >=0.2.0
    - r-whisker
    - r-withr

test:
  commands:
    - $R -e "library('devtools')"  # [not win]
    - "\"%R%\" -e \"library('devtools')\""  # [win]

about:
  home: https://github.com/hadley/devtools
  license: GPL (>= 2)
  summary: Collection of package development tools.
  license_family: GPL3

extra:
  recipe-maintainers:
    - jdblischak
    - johanneskoester
    - bgruening
