{% set version = "2.5.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-devtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/devtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/devtools/devtools_{{ version }}.tar.gz
  sha256: f677dd7d527f0e2184818edfba9bb45668e2985b76b4f5517c7ad6cff42317a2

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.6.6
    - r-desc >=1.4.3
    - r-ellipsis >=0.3.3
    - r-fs >=2.0.1
    - r-lifecycle >=1.0.5
    - r-memoise >=2.0.1
    - r-miniui >=0.1.2
    - r-pak >=0.9.3
    - r-pkgbuild >=1.4.8
    - r-pkgdown >=2.2.0
    - r-pkgload >=1.5.1
    - r-profvis >=0.4.0
    - r-rcmdcheck >=1.4.0
    - r-rlang >=1.2.0
    - r-roxygen2 >=7.3.3
    - r-rversions >=3.0.0
    - r-sessioninfo >=1.2.3
    - r-testthat >=3.3.2
    - r-urlchecker >=1.0.1
    - r-usethis >=3.2.1
    - r-withr >=3.0.2
  run:
    - r-base
    - r-cli >=3.6.6
    - r-desc >=1.4.3
    - r-ellipsis >=0.3.3
    - r-fs >=2.0.1
    - r-lifecycle >=1.0.5
    - r-memoise >=2.0.1
    - r-miniui >=0.1.2
    - r-pak >=0.9.3
    - r-pkgbuild >=1.4.8
    - r-pkgdown >=2.2.0
    - r-pkgload >=1.5.1
    - r-profvis >=0.4.0
    - r-rcmdcheck >=1.4.0
    - r-rlang >=1.2.0
    - r-roxygen2 >=7.3.3
    - r-rversions >=3.0.0
    - r-sessioninfo >=1.2.3
    - r-testthat >=3.3.2
    - r-urlchecker >=1.0.1
    - r-usethis >=3.2.1
    - r-withr >=3.0.2

test:
  commands:
    - $R -e "library('devtools')"           # [not win]
    - "\"%R%\" -e \"library('devtools')\""  # [win]

about:
  home: https://devtools.r-lib.org/
  dev_url: https://github.com/r-lib/devtools
  license: MIT
  summary: Collection of package development tools.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
