{% set version = '2.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-devtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/devtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/devtools/devtools_{{ version }}.tar.gz
  sha256: 2e988fb56b068ba958ea471224d2462427868ce7706e157a90c0ce0e13294e44

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dt
    - r-callr
    - r-cli
    - r-covr >=3.2.0
    - r-crayon
    - r-desc
    - r-digest
    - r-ellipsis >=0.3.0
    - r-git2r >=0.23.0
    - r-glue
    - r-httr >=0.4
    - r-jsonlite
    - r-memoise >=1.0.0
    - r-pkgbuild >=1.0.3
    - r-pkgload >=1.0.2
    - r-rcmdcheck >=1.3.3
    - r-remotes >=2.1.0
    - r-rlang
    - r-roxygen2 >=6.1.1
    - r-rstudioapi >=0.7
    - r-rversions
    - r-sessioninfo >=1.1.1
    - r-testthat >=2.1.1
    - r-usethis >=1.5.0
    - r-withr
  run:
    - r-base
    - r-dt
    - r-callr
    - r-cli
    - r-covr >=3.2.0
    - r-crayon
    - r-desc
    - r-digest
    - r-ellipsis >=0.3.0
    - r-git2r >=0.23.0
    - r-glue
    - r-httr >=0.4
    - r-jsonlite
    - r-memoise >=1.0.0
    - r-pkgbuild >=1.0.3
    - r-pkgload >=1.0.2
    - r-rcmdcheck >=1.3.3
    - r-remotes >=2.1.0
    - r-rlang
    - r-roxygen2 >=6.1.1
    - r-rstudioapi >=0.7
    - r-rversions
    - r-sessioninfo >=1.1.1
    - r-testthat >=2.1.1
    - r-usethis >=1.5.0
    - r-withr

test:
  commands:
    - $R -e "library('devtools')"           # [not win]
    - "\"%R%\" -e \"library('devtools')\""  # [win]

about:
  home: https://github.com/r-lib/devtools
  license: GPL-2
  summary: Collection of package development tools.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: devtools
# Title: Tools to Make Developing R Packages Easier
# Version: 2.2.1
# Authors@R: c( person("Hadley", "Wickham", role = "aut"), person("Jim", "Hester", , "jim.hester@rstudio.com", role = c("aut", "cre")), person("Winston", "Chang", role = "aut"), person("RStudio", role = "cph"), person("R Core team", role = "ctb", comment = "Some namespace and vignette code extracted from base R") )
# Description: Collection of package development tools.
# License: GPL (>= 2)
# URL: https://github.com/r-lib/devtools
# BugReports: https://github.com/r-lib/devtools/issues
# Depends: R (>= 3.0.2), usethis (>= 1.5.0)
# Imports: callr, cli, covr (>= 3.2.0), crayon, desc, digest, DT, ellipsis (>= 0.3.0), glue, git2r (>= 0.23.0), httr (>= 0.4), jsonlite, memoise (>= 1.0.0), pkgbuild (>= 1.0.3), pkgload (>= 1.0.2), rcmdcheck (>= 1.3.3), remotes (>= 2.1.0), rlang, roxygen2 (>= 6.1.1), rstudioapi (>= 0.7), rversions, sessioninfo (>= 1.1.1), stats, testthat (>= 2.1.1), tools, utils, withr
# Suggests: BiocManager, bitops, curl (>= 0.9), evaluate, foghorn (>= 1.1.0), gmailr (> 0.7.0), knitr, lintr (>= 0.2.1), mockery, pingr, MASS, pkgdown, Rcpp (>= 0.10.0), rhub (>= 1.0.2), rmarkdown, spelling (>= 1.1), whisker
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Language: en-US
# NeedsCompilation: no
# Packaged: 2019-09-24 13:01:37 UTC; jhester
# Author: Hadley Wickham [aut], Jim Hester [aut, cre], Winston Chang [aut], RStudio [cph], R Core team [ctb] (Some namespace and vignette code extracted from base R)
# Maintainer: Jim Hester <jim.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-24 15:00:02 UTC
