{% set version = '2.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-devtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/devtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/devtools/devtools_{{ version }}.tar.gz
  sha256: 4fc375c171335c67bd71df4e0b1b3dff2ae3aa17b3e0566b790ba0808b39dcd0

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dt >=0.13
    - r-callr >=3.4.3
    - r-cli >=2.0.2
    - r-covr >=3.5.0
    - r-crayon >=1.3.4
    - r-desc >=1.2.0
    - r-digest >=0.6.25
    - r-ellipsis >=0.3.0
    - r-git2r >=0.26.1
    - r-glue >=1.4.0
    - r-httr >=1.4.1
    - r-jsonlite >=1.6.1
    - r-memoise >=1.1.0
    - r-pkgbuild >=1.0.6
    - r-pkgload >=1.0.2
    - r-rcmdcheck >=1.3.3
    - r-remotes >=2.1.1
    - r-rlang >=0.4.5
    - r-roxygen2 >=7.1.0
    - r-rstudioapi >=0.11
    - r-rversions >=2.0.1
    - r-sessioninfo >=1.1.1
    - r-testthat >=2.3.2
    - r-usethis >=1.6.0
    - r-withr >=2.1.2
  run:
    - r-base
    - r-dt >=0.13
    - r-callr >=3.4.3
    - r-cli >=2.0.2
    - r-covr >=3.5.0
    - r-crayon >=1.3.4
    - r-desc >=1.2.0
    - r-digest >=0.6.25
    - r-ellipsis >=0.3.0
    - r-git2r >=0.26.1
    - r-glue >=1.4.0
    - r-httr >=1.4.1
    - r-jsonlite >=1.6.1
    - r-memoise >=1.1.0
    - r-pkgbuild >=1.0.6
    - r-pkgload >=1.0.2
    - r-rcmdcheck >=1.3.3
    - r-remotes >=2.1.1
    - r-rlang >=0.4.5
    - r-roxygen2 >=7.1.0
    - r-rstudioapi >=0.11
    - r-rversions >=2.0.1
    - r-sessioninfo >=1.1.1
    - r-testthat >=2.3.2
    - r-usethis >=1.6.0
    - r-withr >=2.1.2

test:
  commands:
    - $R -e "library('devtools')"           # [not win]
    - "\"%R%\" -e \"library('devtools')\""  # [win]

about:
  home: https://devtools.r-lib.org/, https://github.com/r-lib/devtools
  license: GPL-2.0-or-later
  summary: Collection of package development tools.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: devtools
# Title: Tools to Make Developing R Packages Easier
# Version: 2.3.0
# Authors@R: c( person("Hadley", "Wickham", role = "aut"), person("Jim", "Hester", , "jim.hester@rstudio.com", role = c("aut", "cre")), person("Winston", "Chang", role = "aut"), person("RStudio", role = "cph"), person("R Core team", role = "ctb", comment = "Some namespace and vignette code extracted from base R") )
# Description: Collection of package development tools.
# License: GPL (>= 2)
# URL: https://devtools.r-lib.org/, https://github.com/r-lib/devtools
# BugReports: https://github.com/r-lib/devtools/issues
# Depends: R (>= 3.0.2), usethis (>= 1.6.0)
# Imports: callr (>= 3.4.3), cli (>= 2.0.2), covr (>= 3.5.0), crayon (>= 1.3.4), desc (>= 1.2.0), digest (>= 0.6.25), DT (>= 0.13), ellipsis (>= 0.3.0), glue (>= 1.4.0), git2r (>= 0.26.1), httr (>= 1.4.1), jsonlite (>= 1.6.1), memoise (>= 1.1.0), pkgbuild (>= 1.0.6), pkgload (>= 1.0.2), rcmdcheck (>= 1.3.3), remotes (>= 2.1.1), rlang (>= 0.4.5), roxygen2 (>= 7.1.0), rstudioapi (>= 0.11), rversions (>= 2.0.1), sessioninfo (>= 1.1.1), stats, testthat (>= 2.3.2), tools, utils, withr (>= 2.1.2)
# Suggests: BiocManager (>= 1.30.10), curl (>= 4.3), foghorn (>= 1.1.5), gmailr (>= 1.0.0), knitr (>= 1.28), lintr (>= 2.0.1), mockery (>= 0.4.2), pingr (>= 2.0.0), MASS, pkgdown (>= 1.5.1), rhub (>= 1.1.1), rmarkdown (>= 2.1), spelling (>= 2.1)
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 7.1.0
# Language: en-US
# NeedsCompilation: no
# Packaged: 2020-04-09 17:12:11 UTC; jhester
# Author: Hadley Wickham [aut], Jim Hester [aut, cre], Winston Chang [aut], RStudio [cph], R Core team [ctb] (Some namespace and vignette code extracted from base R)
# Maintainer: Jim Hester <jim.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-04-10 23:20:11 UTC
