{% set version = "2.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-devtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/devtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/devtools/devtools_{{ version }}.tar.gz
  sha256: c1f75346a90adf0669b5508fe68cc78bd3b114c1303fa7d22bf90991edd9230d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-callr
    - r-cli
    - r-digest
    - r-git2r >=0.23.0
    - r-httr >=0.4
    - r-jsonlite
    - r-memoise >=1.0.0
    - r-pkgbuild >=1.0.2
    - r-pkgload >=1.0.1
    - r-rcmdcheck >=1.3.2
    - r-remotes >=2.0.2
    - r-rstudioapi >=0.6.0.9000
    - r-sessioninfo
    - r-usethis >=1.4.0
    - r-withr
  run:
    - r-base
    - r-callr
    - r-cli
    - r-digest
    - r-git2r >=0.23.0
    - r-httr >=0.4
    - r-jsonlite
    - r-memoise >=1.0.0
    - r-pkgbuild >=1.0.2
    - r-pkgload >=1.0.1
    - r-rcmdcheck >=1.3.2
    - r-remotes >=2.0.2
    - r-rstudioapi >=0.6.0.9000
    - r-sessioninfo
    - r-usethis >=1.4.0
    - r-withr

test:
  commands:
    - $R -e "library('devtools')"           # [not win]
    - "\"%R%\" -e \"library('devtools')\""  # [win]

about:
  home: https://github.com/r-lib/devtools
  license: GPL (>= 2)
  summary: Collection of package development tools.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: devtools
# Title: Tools to Make Developing R Packages Easier
# Version: 2.0.2
# Authors@R: c( person("Hadley", "Wickham", role = "aut"), person("Jim", "Hester", , "james.hester@rstudio.com", role = c("aut", "cre")), person("Winston", "Chang", role = "aut"), person("RStudio", role = "cph"), person("R Core team", role = "ctb", comment = "Some namespace and vignette code extracted from base R") )
# Description: Collection of package development tools.
# License: GPL (>= 2)
# URL: https://github.com/r-lib/devtools
# BugReports: https://github.com/r-lib/devtools/issues
# Depends: R (>= 3.0.2)
# Imports: callr, cli, digest, git2r (>= 0.23.0), httr (>= 0.4), jsonlite, memoise (>= 1.0.0), pkgbuild (>= 1.0.2), pkgload (>= 1.0.1), rcmdcheck (>= 1.3.2), remotes (>= 2.0.2), rstudioapi (>= 0.6.0.9000), sessioninfo, stats, tools, usethis (>= 1.4.0), utils, withr
# Suggests: BiocManager, bitops, covr (>= 3.2.0), crayon, curl (>= 0.9), evaluate, foghorn (>= 1.1.0), gmailr (> 0.7.0), knitr, lintr (>= 0.2.1), mockery, pingr, MASS, pkgdown, Rcpp (>= 0.10.0), rhub (>= 1.0.2), rmarkdown, roxygen2 (>= 6.1.0), rversions, spelling (>= 1.1), testthat (>= 1.0.2), whisker
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-04-08 15:34:15 UTC; jhester
# Author: Hadley Wickham [aut], Jim Hester [aut, cre], Winston Chang [aut], RStudio [cph], R Core team [ctb] (Some namespace and vignette code extracted from base R)
# Maintainer: Jim Hester <james.hester@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-04-08 20:03:38 UTC
