appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: N2GuM0vBKFD6xhgRDo8Zdc09DgpBD+ASulzmBJCvOfr2sLUBZivhsLxEzUN2Qa1Olq5T8LzFIhyTJ/iAZoAeXNH4uM8Dg1evQ42QZPeIurHZ8Vp4oGuqLMSNvZjWtUDe3Zctlvjh53Yo+tck6UThVp28Z8UOydITI4EUeY6pK2BbKLdVypdHTtCm+FB6IT+GGkPofyWrwSAe78PZK/Uw4KmQ3pKpHsUH+N9FDSpvYPKwBPLCnaW2Ni+HZtgA5cSy6A4AA2rlB4/mn7Ay5lDFEpZX41MZ9W0EwoFuR8O9clYUsjzrW6QTY/G7K2iTyOm7DKlJOd4OIKuu7tjNbhRAK4XN+jnG8GUcb9L4sWH5Z6ZpFz2E3ZhsHobLZ/Rc5bDcrdByBFdz+qgCaq1dBhBT0yY2n2/rMEo3/Q7fQ9HGS9w7AqxtGpjntIUnAbQsypGZV+lMUC0bKY2WpWw4w729zXqqSse3mcNeG+21G4MTnP2Hhk5Kooe1VZpAN1F0oZGVPIeiGg58bDNkjtngdV4YIAyb22qBbTT6aKEN8RESL6IG7is/9GTQBWHR7YaeVs2L5uW8uzD2ii2D4ju02km7sADZ+RkhjZQEukGieX0Ir71zehVi4PqnAeOD3VKNgbuSSnPzwNa1walU5iKfMxDKU+m9c2FHDroQy5+lHCzXBSs=
